use actix_web::web;

pub fn init(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/work_contracts")
            .route(
                "",
                web::get().to(crate::handlers::work_contract_handlers::get_work_contracts),
            )
            .route(
                "",
                web::post().to(crate::handlers::work_contract_handlers::upload_work_contract),
            )
            .route(
                "/{id}",
                web::put().to(crate::handlers::work_contract_handlers::update_work_contract),
            )
            .route(
                "/{id}",
                web::delete().to(crate::handlers::work_contract_handlers::delete_work_contract),
            )
            .route(
                "/{id}/files",
                web::post().to(crate::handlers::work_contract_handlers::upload_work_contract_files),
            )
            .route(
                "/categories",
                web::get()
                    .to(crate::handlers::work_contract_handlers::get_work_contract_categories),
            )
            .route(
                "/categories",
                web::post().to(crate::handlers::work_contract_handlers::add_work_contract_category),
            )
            .route(
                "/categories/{id}",
                web::put()
                    .to(crate::handlers::work_contract_handlers::update_work_contract_category),
            )
            .route(
                "/categories/{id}",
                web::delete()
                    .to(crate::handlers::work_contract_handlers::delete_work_contract_category),
            ),
    );
}
